# Project Info
site_name: 'BluebirdPS'
site_description: 'Online Help for BluebirdPS PowerShell Module'
site_author: 'Dave Carroll'
site_url: 'https://bluebirdps.anovelidea.org'

# Repo Info
repo_name: 'thedavecarroll/BluebirdPS'
repo_url: 'https://github.com/thedavecarroll/BluebirdPS'
#edit_uri: 'edit/master/docs/'

# Copyright
copyright: "Copyright &copy; 2020 Dave Carroll<br/>BluebirdPS is licensed under the <a href=https://github.com/thedavecarroll/BluebirdPS/raw/main/LICENSE>MIT license."

# Analytics
google_analytics:
  - 'UA-122236350-3'
  - 'auto'

# Configuration
theme:
  name: material
  language: 'en'
  palette:
      primary: 'light blue'
      accent: 'indigo'
  font:
      text: 'Roboto'
      code: 'Roboto Mono'
  features:
    - navigation.tabs

# Customization
extra:
  social:
    - type: github
      link: https://github.com/thedavecarroll/
    - type: twitter
      link: https://twitter.com/thedavecarroll
    - type: linkedin
      link: https://www.linkedin.com/in/thedavecarroll/